export const CREATE_COLUMN = "CREATE_COLUMN";
export const RETRIEVE_COLUMNS = "RETRIEVE_COLUMNS";
export const UPDATE_COLUMN = "UPDATE_COLUMN";
export const DELETE_COLUMN = "DELETE_COLUMN";
export const DELETE_ALL_COLUMNS = "DELETE_ALL_COLUMNS";